services:
  chroma:
    image: 'chromadb/chroma:latest'
    ports:
      - '8000:8000'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:



